Repository RollingPaper42/Back-End, pull requests merged in 2023-11, with the labels that each got.

#5 feat: 구글 OAuth 로그인 및 JWT 발급과 인증 로직 구현
  build.gradle
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/config/SpringConfig.java
  src/main/java/com/strcat/config/oauth/JwtAuthFilter.java
  src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
  src/main/java/com/strcat/controller/MainController.java
  src/main/java/com/strcat/domain/OAuthUser.java
  src/main/java/com/strcat/domain/User.java
  src/main/java/com/strcat/repository/OAuthUserRepository.java
  src/main/java/com/strcat/repository/UserRepository.java
  src/main/java/com/strcat/service/OAuthProviderEnum.java
  src/main/java/com/strcat/service/OAuthUserService.java
  src/main/java/com/strcat/util/JwtUtils.java
  temp
Labels: ✨ feature

#10 fix: OAuthUserService 분기문 오류 수정
  src/main/java/com/strcat/service/OAuthUserService.java
Labels: 🐞 bug

#11 feat: CORS 설정을 위한 WebCofig 추가 #9
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/config/WebConfig.java
Labels: ✨ feature

#13 [Feat] lombok 적용을 위한 기존 코드 수정 #12
  build.gradle
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/domain/OAuthUser.java
  src/main/java/com/strcat/domain/User.java
  src/main/java/com/strcat/service/OAuthUserService.java
Labels: ✨ feature

#15 [Fix] git conflict 수정
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/service/OAuthUserService.java
Labels: 🔨 fix

#16 chore: deploy.yml 수정
  .github/workflows/deploy.yml
Labels: ⚙️ chore

#18 [Fix] deploy.yml에서 submodule 이름 수정
  .github/workflows/deploy.yml
Labels: 🔨 fix

#22 feat: JwtAuthenticationEntryPoint 구현 및 ExceptionResolver 구현
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/config/oauth/JwtAuthFilter.java
  src/main/java/com/strcat/config/oauth/JwtAuthenticationEntryPoint.java
  src/main/java/com/strcat/config/oauth/OAuthFailureHandler.java
  src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
  src/main/java/com/strcat/config/oauth/UnauthorizedExceptionHandlerFilter.java
  src/main/java/com/strcat/exception/ExceptionResolver.java
  src/main/java/com/strcat/exception/ResponseException.java
  src/main/java/com/strcat/exception/UnauthorizedException.java
Labels: ✨ feature

#28 feat: Implement a board
  src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
  src/main/java/com/strcat/controller/BoardController.java
  src/main/java/com/strcat/domain/Board.java
  src/main/java/com/strcat/domain/Content.java
  src/main/java/com/strcat/dto/CreateBoardReqDto.java
  src/main/java/com/strcat/dto/ReadBoardInfoResDto.java
  src/main/java/com/strcat/dto/ReadBoardSummaryResDto.java
  src/main/java/com/strcat/service/BoardService.java
  src/main/java/com/strcat/service/OAuthUserService.java
  src/main/java/com/strcat/util/AesSecretUtils.java
  src/main/java/com/strcat/util/JwtUtils.java
  src/test/java/com/strcat/oauth/ContentServiceTest.java
Labels: ✨ feature

#29 refactor: PR 피드백 적용
  src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
  src/main/java/com/strcat/service/BoardService.java
  src/main/java/com/strcat/util/JwtUtils.java
Labels: ♻️ refactor

#51 Fix/add substring method in jwt utils#47
  src/main/java/com/strcat/service/UserService.java
  src/main/java/com/strcat/util/JwtUtils.java
Labels: 🐞 bug, 🔨 fix

#57 fix: BoardService 생성자 변화를 테스트에 적용
  src/test/java/com/strcat/oauth/BoardServiceTest.java
Labels: 🔨 fix

#56 chore: Swagger 적용
  build.gradle
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/config/SwaggerConfig.java
  src/main/java/com/strcat/controller/BoardController.java
Labels: ⚙️ chore

#64 fix: redirectUrl 변경 및 쿼리 파라미터로 토큰 전달
  src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
Labels: 🔨 fix

#74 feat: board group api 병합#71
  src/main/java/com/strcat/controller/BoardGroupController.java
  src/main/java/com/strcat/dto/ReadBoardGroupBoardInfoResDto.java
  src/main/java/com/strcat/dto/ReadBoardGroupResDto.java
  src/main/java/com/strcat/repository/BoardGroupRepository.java
  src/main/java/com/strcat/repository/ContentRepository.java
  src/main/java/com/strcat/service/BoardGroupService.java
Labels: ✨ feature

#77 feat: 보드 요약 조회 api에 theme 추가 #75
  src/main/java/com/strcat/dto/ReadBoardSummaryResDto.java
  src/main/java/com/strcat/service/BoardService.java
Labels: ✨ feature

#83 fix: Dto 생성자 변경에 따른 테스트 수정
  src/test/java/com/strcat/oauth/BoardServiceTest.java
Labels: 🔨 fix

#82 feat: swagger 관련 어노테이션 추가 및 WHITE_LIST 수정
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/controller/BoardController.java
  src/main/java/com/strcat/controller/BoardGroupController.java
  src/main/java/com/strcat/controller/LoginController.java
  src/main/java/com/strcat/controller/MainController.java
Labels: ⚙️ chore, ✨ feature

#89 feat: content POST 요청 시 생성된 content id값 반환하도록 변경함
  src/main/java/com/strcat/controller/BoardController.java
Labels: ✨ feature

#94 feat: Read my board info encrypted id 및 theme 추가 구현
  src/main/java/com/strcat/controller/UserController.java
  src/main/java/com/strcat/dto/ReadMyBoardInfoResDto.java
  src/main/java/com/strcat/repository/BoardRepository.java
  src/main/java/com/strcat/service/BoardService.java
Labels: ✨ feature

#92 feat: 내 보드그룹 정보 조회 api 구현
  src/main/java/com/strcat/controller/UserController.java
  src/main/java/com/strcat/dto/TmpReadMyBoardGroupInfoResDto.java
  src/main/java/com/strcat/repository/BoardGroupRepository.java
  src/main/java/com/strcat/service/BoardGroupService.java
Labels: ✨ feature

#90 fix: api path에서 불필요한 부분 삭제 및 WHITE_LIST 수정
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/controller/BoardController.java
  src/main/java/com/strcat/controller/BoardGroupController.java
Labels: 🔨 fix

#95 fix: UserController 누락된 괄호 추가함
  src/main/java/com/strcat/controller/UserController.java
Labels: 🔨 fix

#97 fix: 조회 api에서 token이 없을때 에러 수정
  src/main/java/com/strcat/controller/BoardController.java
  src/main/java/com/strcat/controller/BoardGroupController.java
  src/main/java/com/strcat/service/BoardGroupService.java
  src/main/java/com/strcat/service/BoardService.java
Labels: 🔨 fix

#98 feat: BoardGroupServiceTest 구현
  src/main/java/com/strcat/domain/Board.java
  src/main/java/com/strcat/domain/BoardGroup.java
  src/main/java/com/strcat/domain/Content.java
  src/main/java/com/strcat/dto/ReadBoardGroupResDto.java
  src/main/java/com/strcat/dto/ReadBoardGroupSummaryResDto.java
  src/test/java/com/strcat/board/BoardGroupServiceTest.java
  src/test/java/com/strcat/board/BoardServiceTest.java
  src/test/java/com/strcat/board/ContentServiceTest.java
  src/test/java/com/strcat/utils/TestUtils.java
Labels: ✨ feature, 🔍 test

#99 refactor: AesSecretUtils에서 SecureDataUtils로 알고리즘에 의존적이지 않도록 이름을 변경함
  src/main/java/com/strcat/service/BoardGroupService.java
  src/main/java/com/strcat/service/BoardService.java
  src/main/java/com/strcat/service/ContentService.java
  src/main/java/com/strcat/util/SecureDataUtils.java
  src/test/java/com/strcat/board/BoardGroupServiceTest.java
  src/test/java/com/strcat/board/BoardServiceTest.java
  src/test/java/com/strcat/board/ContentServiceTest.java
Labels: ♻️ refactor

#109 Feat/change encryption logic#108
  src/main/java/com/strcat/util/SecureDataUtils.java
Labels: ✨ feature

#117 Feat/add encrypted id in response about read board and board group#112
  src/main/java/com/strcat/controller/BoardController.java
  src/main/java/com/strcat/controller/BoardGroupController.java
  src/main/java/com/strcat/domain/Board.java
  src/main/java/com/strcat/domain/BoardGroup.java
  src/main/java/com/strcat/dto/ReadBoardGroupResDto.java
  src/main/java/com/strcat/service/BoardGroupService.java
  src/main/java/com/strcat/service/BoardService.java
  src/test/java/com/strcat/board/BoardGroupServiceTest.java
Labels: ✨ feature

#114 feat: AOP를 통한 함수 호출 시간 측정 기능 구현
  src/main/java/com/strcat/aop/TimeTraceAop.java
  src/main/java/com/strcat/config/SpringConfig.java
Labels: ✨ feature

#120 fix: 프론트 요청으로 유저의 보드정보 관련 API dto를 하나로 통일
  src/main/java/com/strcat/config/WebConfig.java
  src/main/java/com/strcat/controller/UserController.java
  src/main/java/com/strcat/dto/ReadMyInfoResDto.java
  src/main/java/com/strcat/dto/TmpReadMyBoardGroupInfoResDto.java
  src/main/java/com/strcat/service/BoardGroupService.java
  src/main/java/com/strcat/service/BoardService.java
Labels: 🔨 fix

#127 fix: api 응답 변경으로 깨진 테스트 수정
  src/main/java/com/strcat/dto/BoardResponse.java
  src/main/java/com/strcat/dto/ReadBoardResDto.java
  src/main/java/com/strcat/service/BoardService.java
  src/test/java/com/strcat/board/BoardGroupServiceTest.java
  src/test/java/com/strcat/board/BoardServiceTest.java
Labels: 🔨 fix

#128 fix: redirect_uri 환경변수 호출부 수정
  src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
Labels: 🔨 fix

#130 Refactor/response of read board group and board#122
  src/main/java/com/strcat/service/BoardGroupService.java
  src/main/java/com/strcat/service/BoardService.java
  src/test/java/com/strcat/board/BoardGroupServiceTest.java
Labels: ♻️ refactor

#134 fix: picture exception 주석처리
  src/main/java/com/strcat/service/PictureService.java
Labels: 🔨 fix
