Repository RollingPaper42/Back-End, pull requests merged in 2024-01, with the labels that each got.

#142 feat: isOwner 확인 테스트 작성#141
  src/test/java/com/strcat/board/BoardGroupServiceTest.java
  src/test/java/com/strcat/board/BoardServiceTest.java
Labels: 🔍 test

#159 chore: README.md 내용 추가
  README.md
Labels: ⚙️ chore

#171 fix: BoardServiceTest에서 conflict를 잘못 해결하여 깨진 테스트 수정
  src/test/java/com/strcat/board/BoardServiceTest.java
Labels: 🔨 fix

#174 refactor: 보드그룹 기능 삭제로 관련 코드 제거
  src/main/java/com/strcat/controller/BoardGroupController.java
  src/main/java/com/strcat/controller/UserController.java
  src/main/java/com/strcat/domain/Board.java
  src/main/java/com/strcat/domain/BoardGroup.java
  src/main/java/com/strcat/domain/User.java
  src/main/java/com/strcat/dto/CreateBoardGroupReqDto.java
  src/main/java/com/strcat/dto/CreateBoardReqDto.java
  src/main/java/com/strcat/dto/ReadBoardGroupResDto.java
  src/main/java/com/strcat/dto/ReadBoardGroupSummaryResDto.java
  src/main/java/com/strcat/repository/BoardGroupRepository.java
  src/main/java/com/strcat/service/BoardGroupService.java
  src/main/java/com/strcat/service/BoardService.java
  src/test/java/com/strcat/board/BoardGroupServiceTest.java
  src/test/java/com/strcat/board/BoardServiceTest.java
Labels: ♻️ refactor

#175 fix, refactor: 불필요한 쿼리가 중복으로 호출되는 문제 해결
  src/main/java/com/strcat/config/SecurityConfig.java
  src/main/java/com/strcat/config/oauth/JwtAuthFilter.java
  src/main/java/com/strcat/service/UserService.java
  src/main/java/com/strcat/util/JwtUtils.java
Labels: 🔨 fix, ♻️ refactor

#179 refactor: short_url 기능 삭제 #165
  src/main/java/com/strcat/controller/ShareController.java
Labels: ♻️ refactor

#180 refactor: PictureService와 ContentService 통합
  src/main/java/com/strcat/controller/BoardController.java
  src/main/java/com/strcat/service/ContentService.java
  src/main/java/com/strcat/service/PictureService.java
  src/test/java/com/strcat/board/ContentServiceTest.java
Labels: ♻️ refactor

#182 refactor: Board에서 처리할 수 있는 dto관련 메서드들을 BoardService에서 Board로 이동함
  src/main/java/com/strcat/domain/Board.java
  src/main/java/com/strcat/service/BoardService.java
Labels: ♻️ refactor
